# This 3 stage ci pipeline is purpose-built for cdk in typescript
# it also includes support for python lambdas
# it implements a basic build, static check, and deploy process
# it also implements e2e and ckditten regional deployment tests
# these tests only run with merge to main
# this pipeline can be removed if and when this repo moves to github


stages:          # List of stages for jobs, and their order of execution
  - docs
  - build
  - static
  - web
  - infra
  - functional
  - validate
  - deploy

variables:
  PYTHON_SCRIPTS: bin/stats
  TS_SCRIPTS: bin/stats
  SHELL_SCRIPTS: bin/validate-config

build-docs:
  stage: docs
  image: registry.gitlab.aws.dev/aws-energy-solutions/area/cross-cutting-solutions/cdk-powertools-build-image
  script:
    - echo "Convert all docs to asciidocs"
    - echo "push them to docs-edit repo branch"
    - echo "done!"

build-cdk:       # Validates that cdk will build, install dependencies, and that cdk with synth
  stage: build
  image: registry.gitlab.aws.dev/aws-energy-solutions/area/cross-cutting-solutions/cdk-powertools-build-image
  script:
    - npm ci
    - echo "succesfully installed package dependencies!"
    - echo "Building with npm..."
    - npm run build
    - echo "Build complete."
    - echo "Synthesizing CDK"
    - cdk synth
    - echo "Completed build check"

build-amplify:       # Validates that cdk will build, install dependencies, and that cdk with synth
  stage: build
  image: registry.gitlab.aws.dev/aws-energy-solutions/area/cross-cutting-solutions/cdk-powertools-build-image
  script:
    - node --version
    - npm ci
    - echo "succesfully installed package dependencies!"
    - echo "Building with npm..."
    - cd front-end/carbonlake-ui-cloudscape
    - pwd
    - npm install
    - wait
    - npm run build
    - wait
    - echo "amplify test successful"

tslint-test-job:   # Runs eslint for typescript to validate linting of typescript code
  stage: static
  image: registry.gitlab.aws.dev/aws-energy-solutions/area/cross-cutting-solutions/cdk-powertools-build-image
  script:
    - npm ci
    - echo "succesfully installed package dependencies!"
    - echo "Building with npm..."
    - npm run build
    - echo "Build complete."
    - echo "Linting code... This will take about 10 seconds."
    - npm run lint
    - echo "No lint issues found."

bandit:   # Runs python bandit test job for security checks on python code in repo
  stage: static    # Only starts when job in build stage completes successfully
  image:
    name: python:latest
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  script:
    - ls -la
    - python --version
    - pip3 install --upgrade pip
    - pip3 install --upgrade setuptools
    - pip3 install bandit
    - bandit ./ -r | tee ./output_test.log

cdk-nag-job:   # runs cdk-nag script in test stage
  stage: static
  image: registry.gitlab.aws.dev/aws-energy-solutions/area/cross-cutting-solutions/cdk-powertools-build-image
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
  script:
    - npm ci
    - echo "succesfully installed package dependencies!"
    - echo "Building with npm..."
    - npm run build
    - echo "Build complete."
    - echo "Running cdk nag to check for security vulnerabilities"
    # - cdk synth --context nag=true <-- nag is removed for now while nag-pack is in development
    - echo "Completed CDK nag check"

amplify-test: # runs test of amplify app
  stage: web
  image: registry.gitlab.aws.dev/aws-energy-solutions/area/cross-cutting-solutions/cdk-powertools-build-image
  only:
    changes:
      - front-end/carbonlake-ui-cloudscape/*/**
  script:
    - aws --version
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile test
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile test
    - aws configure set region $AWS_DEFAULT_REGION --profile test
    - export AWS_PROFILE=test
    - echo $AWS_PROFILE
    - node --version
    - npm ci
    - echo "succesfully installed package dependencies!"
    - echo "Building with npm..."
    - npm run build
    - echo "Build complete."
    - cdk bootstrap
    - cdk synth
    - cdk deploy --all
    - wait
    - echo "Starting Amplify test"
    - sh test-amplify.sh
    - cdk destroy --all --force
    - echo "amplify test successful"

cdk-test: # runs test of amplify app
  stage: infra
  image: registry.gitlab.aws.dev/aws-energy-solutions/area/cross-cutting-solutions/cdk-powertools-build-image
  only:
    changes:
      - lib/*/**
      - bin/*/**
      - cdk.json
  script:
    - aws --version
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile test
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile test
    - aws configure set region $AWS_DEFAULT_REGION --profile test
    - export AWS_PROFILE=test
    - echo $AWS_PROFILE
    - node --version
    - npm ci
    - echo "succesfully installed package dependencies!"
    - echo "Building with npm..."
    - npm run build
    - echo "Build complete."
    - cdk bootstrap
    - cdk synth
    - cdk deploy --all
    - wait
    - echo "Starting Amplify test"
    - sh test-amplify.sh
    - cdk destroy --all --force
    - echo "amplify test successful"

end-to-end-test:   # runs e2e test
  stage: functional
  image: registry.gitlab.aws.dev/aws-energy-solutions/area/cross-cutting-solutions/cdk-powertools-build-image
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
  script:
    - aws --version
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile test
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile test
    - aws configure set region $AWS_DEFAULT_REGION --profile test
    - export AWS_PROFILE=test
    - node --version
    - npm ci
    - echo "succesfully installed package dependencies!"
    - echo "Building with npm..."
    - npm run build
    - echo "Build complete."
    - echo "Running cdk nag to check for security vulnerabilities"
    - cdk synth
    - echo "Starting e2e test"
    - yum install jq -y
    - sh test-e2e.sh
    - echo "e2e test successful"

cdkitten-deploy-job:      # Runs cdkitten deployment job in test AWS accounts
  stage: validate  # It only runs when *both* jobs in the test stage complete successfully.
  image: registry.gitlab.aws.dev/aws-energy-solutions/area/cross-cutting-solutions/cdk-powertools-build-image
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile test
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile test
    - aws configure set region $AWS_DEFAULT_REGION --profile test
    - export AWS_PROFILE=test
    - node --version
    - npm ci
    - echo "succesfully installed package dependencies!"
    - echo "Building with npm..."
    - npm run build
    - echo "Build complete."
    - cdk synth
    - echo "Synthesized!"
    - echo "Running CDKittenðŸ±"
    - sh test-deployment.sh
    - echo "Application deployment placeholder passed"
